Repository fireblade-engine/pal, pull requests merged in 2021-11, with the labels that each got.

#5 Expose scancode for SDL based keys
  .github/workflows/ci-linux.yml
  .github/workflows/ci-macos.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/mlc_config.json
  Sources/FirebladePAL/Platform/SDL/SDLEvents.swift
  Sources/FirebladePAL/Platform/SDL/SDLKeys.swift
Labels: enhancement, ci-all

#6 Add native file dialogs
  Package.resolved
  Package.swift
  Sources/FirebladePAL/Window.swift
Labels: enhancement, ci-all

#7 Fix button equality
  Makefile
  Mintfile
  Package.swift
  Sources/CPUBackendDemoApp/main.swift
  Sources/FirebladePAL/Platform/SDL/SDLEvents.swift
  Sources/FirebladePAL/Platform/SDL/SDLScreen.swift
  Sources/FirebladePAL/Platform/SDL/Surface/SDLVLKWindowSurface.swift
  Sources/FirebladePAL/PointerButton.swift
Labels: bug, ci-all

#8 Add Clipboard handling
  Sources/FirebladePAL/Clipboard.swift
  Sources/FirebladePAL/Platform.swift
  Sources/FirebladePAL/Platform/SDL/SDLClipboard.swift
  Tests/FirebladePALTests/FirebladePALTests.swift
  Tests/FirebladePALTests/XCTestManifests.swift
Labels: enhancement, ci-all

#9 Update SwiftVulkan
  Package.resolved
  Package.swift
Labels: enhancement

#3 fix linux CI
  .github/workflows/ci-linux.yml
  .github/workflows/ci-macos.yml
  .github/workflows/markdown-link-check.yml
Labels: ci-all
